### PR TITLE
Add identifier in request header

### PR DESCRIPTION
**Pull request by mirecl**
👋 Hi guys!
**AS-IS**: identifier insert only response header
**TO-BE**: identifier insert request/response headers

_P.S. I am confident that this commit will be beneficial for the community._

### CODE REVIEW

**Comment by mirecl** [comment]
@vbrandl, what do you think about it?

**Comment by vbrandl** [comment]
Hey @mirecl,
Thanks for your contribution. I'm not quite sure about the benefit of modifying the incoming request headers. We want to propagate the ID to the response, that's why [response header is set](https://github.com/vbrandl/actix-request-identifier/blob/365d94e523a4630fda743b986d07733631291a17/src/lib.rs#L222), but why would you want to modify the request?

**Comment by mirecl** [comment]
@vbrandl, actix-web can be used for example as reverse proxy.
**Example 1** for Proxy:
```
server {
    listen 80;
    add_header X-Request-ID $request_id; # Return to client
    location / {
        proxy_pass http://app_server;
        proxy_set_header X-Request-ID $request_id; # Pass to app server
    }
}
```
❗More information (Nginx): https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id

**Example 2** plugin system (https://github.com/vmware-labs/wasm-workers-server).
❗Send data for wasm module from header

**Comment by vbrandl** [comment]
Ah I see. You want to reuse the request ID, if an incoming request has the `x-request-id` header already set? This can already be done by setting `IdReuse::UseIncoming` when creating the middleware. Have a look [at the example](https://github.com/vbrandl/actix-request-identifier/blob/master/examples/actix-web.rs#L14) (`cargo run --example=actix-web`).

I just checked again, using the following nginx config:

```nginx
server {
    listen       8081;
    server_name  _;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header X-Request-ID '0000-0000-0000-0000';
    }
}
```

```
# call through nginx
$ curl -i http://localhost:8081
HTTP/1.1 200 OK
Server: nginx/1.25.1
Date: Tue, 04 Jul 2023 11:25:48 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19
Connection: keep-alive
x-request-id: 0000-0000-0000-0000

# call directly
$ curl -i http://localhost:8080
HTTP/1.1 200 OK
content-length: 36
content-type: text/plain; charset=utf-8
x-request-id: b2c1cf94-ffb2-4faa-bb49-ce6c294828d0
date: Tue, 04 Jul 2023 11:26:36 GMT

b2c1cf94-ffb2-4faa-bb49-ce6c294828d0


# call directly and pass request header
$ curl -i http://localhost:8080 -H 'x-request-id: 12345'
HTTP/1.1 200 OK
content-length: 5
content-type: text/plain; charset=utf-8
x-request-id: 12345
date: Tue, 04 Jul 2023 11:27:38 GMT

12345
```

**Comment by mirecl** [comment]
@vbrandl, revers proxy (example Nginx) can generate request_id if it is missing. This is used later in the logs of the application itself.

**Comment by vbrandl** [comment]
Yeah and by setting `IdReuse::UseIncoming` in the middleware, the actix-web application will use the ID generated and passed by nginx.

So if you set `proxy_set_header X-Request-ID $request_id;` in your nginx config, nginx will generate a request ID, pass it to the actix-web application and with `IdReuse::UseIncoming`, the application will use that as the ID.

I'm still not quite sure, what you want to achieve...

**Comment by mirecl** [comment]
I'm create custom reverse proxy with actix-web and I need generation request_id and change request header)

**Comment by vbrandl** [comment]
The request header is already generated in the middleware or, depending on the middleware configuration, an incoming request id is used.

Can you give me an example of requests and expected behavior you'd like to see, that is currently not possible?

If you want to use the request id (either the generated one, or the one extracted from the incoming request), you can use the `RequestId` extractor in your endpoints like this:

```rust
#[get("/")]
async fn show_request_id(id: RequestId) -> impl Responder {
    // id is the generated or extracted id
    format!("{}", id.as_str())
}
```

If you want to access the request id inside another middleware, it can be done like this (note that the `RequestIdentifier` middleware must come _after_ the middleware that uses the request id):

```rust
App::new()
    .service(show_request_id)
    .wrap_fn(|req, srv| {
        {
            let ext = req.extensions();
            let id = ext.get::<RequestId>().unwrap();
            println!("From Middleware: id = {}", id.as_str());
        }
        srv.call(req)
    })
    .wrap(RequestIdentifier::with_uuid().use_incoming_id(IdReuse::UseIncoming))
```

**Comment by vbrandl** [comment]
Were you able to solve your problem?

**Comment by mirecl** [comment]
@vbrandl , yes) 👍

**Comment by vbrandl** [comment]
Is there anything I could make more clear in the documentation or examples? Otherwise I'll close this PR

**Pull request closed without merging**
